# whitelist
branches:
  only:
    - travis_test

langauge: java

jdk:
  - oraclejdk8

install: echo 'Skipping mvn install'

before_script:
 - chmod +x build/travis.sh
 - echo "MAVEN_OPTS='-Xmx2g -Xms1g'" > ~/.mavenrc

script:
 - mvn clean verify -fcore/pom.xml -Declipse.p2.mirrors=false -Dtycho.localArtifacts=ignore -Pcheckstyle
 - mvn clean verify -fapplications/pom.xml -Declipse.p2.mirrors=false -Dtycho.localArtifacts=ignore -Pcheckstyle -Dcsstudio.composite.repo=core/p2repo

after_success:
 - build/travis.sh | xargs -I {} -n1 mvn clean verify -f{} -Declipse.p2.mirrors=false -Dtycho.localArtifacts=ignore -Pcheckstyle -Dcsstudio.composite.repo=p2repo -Pupload
