# whitelist

langauge: java

sudo: false

dist: trusty

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8

install: echo 'Skipping mvn install'

before_script:
 - chmod +x build/travis.sh
 - echo "MAVEN_OPTS='-Xmx2g -Xms1g'" > ~/.mavenrc

script:
 - java -version
 - ./build/travis.sh 
